name: Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Requirements
      run: |
        sudo apt-get update
        sudo apt-get install doxygen
        pip3 install -r docsDoxySphinx/requirements.txt
    
    - name: Build docs
      run: |
        cd docsDoxySphinx
        make html